name: io_flip_ui
description: UI Toolkit for IO FLIP.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-417.3.beta <4.0.0"
  flutter: 3.10.0-1.4.pre

dependencies:
  equatable: ^2.0.5
  flame:
    git:
      url: https://github.com/willhlas/flame
      path: packages/flame
      ref: main
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.1
  flutter_svg: ^2.0.5
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^4.0.0

flutter:
  shaders:
    - shaders/foil.frag

  assets:
    - assets/images/
    - assets/images/elements/desktop/air/
    - assets/images/elements/desktop/earth/
    - assets/images/elements/desktop/fire/
    - assets/images/elements/desktop/metal/
    - assets/images/elements/desktop/water/
    - assets/images/elements/mobile/air/
    - assets/images/elements/mobile/earth/
    - assets/images/elements/mobile/fire/
    - assets/images/elements/mobile/metal/
    - assets/images/elements/mobile/water/
    - assets/images/result_badges/
    - assets/images/suits/onboarding/
    - assets/images/suits/card/
    - assets/images/card_frames/

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSansText-Regular.ttf
        - asset: assets/fonts/GoogleSansText-Italic.ttf
          style: italic
    - family: Roboto Serif
      fonts:
        - asset: assets/fonts/RobotoSerif-Regular.ttf
        - asset: assets/fonts/RobotoSerif-Italic.ttf
          style: italic
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira-Regular.ttf
        - asset: assets/fonts/Saira-Italic.ttf
          style: italic

flutter_gen:
  line_length: 80
  assets:
    outputs:
      package_parameter_enabled: true

  integrations:
    flutter_svg: true
