name: api_client
description: Client to access the api
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-134.0.dev <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

dependencies:
  encrypt: ^5.0.1
  game_domain:
    path: ../../api/packages/game_domain
  http: ^0.13.5
  web_socket_client: ^0.1.0-dev.3
