name: top_dash
description: Google I/Os Top Dash game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.10.0-1.1.pre

dependencies:
  api_client:
    path: packages/api_client
  audioplayers: ^3.0.1
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.1
  cloud_firestore: ^4.5.0
  code_text_field: ^1.1.0
  collection: ^1.17.0
  connection_repository:
    path: packages/connection_repository
  equatable: ^2.0.5
  firebase_app_check: ^0.1.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.5.0
  firebase_crashlytics: ^3.1.0
  firebase_storage: ^11.1.0
  flame:
    git:
      url: https://github.com/willhlas/flame
      path: packages/flame
      ref: main
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  game_domain:
    path: api/packages/game_domain
  game_script_machine:
    path: api/packages/game_script_machine
  go_router: ^6.5.5
  highlight: ^0.7.0
  intl: ^0.18.0
  logging: ^1.1.1
  match_maker_repository:
    path: packages/match_maker_repository
  provider: ^6.0.5
  share_plus: ^6.3.1
  shared_preferences: ^2.1.0
  styled_text: ^7.0.0
  top_dash_ui:
    path: packages/top_dash_ui
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  fake_async: ^1.3.1
  flutter_gen_runner: ^5.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^4.0.0

dependency_overrides:
  intl: ^0.17.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/leaderboard/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSansText-Regular.ttf
        - asset: assets/fonts/GoogleSansText-Italic.ttf
          style: italic
    - family: Roboto Serif
      fonts:
        - asset: assets/fonts/RobotoSerif-Regular.ttf
        - asset: assets/fonts/RobotoSerif-Italic.ttf
          style: italic
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira-Regular.ttf
        - asset: assets/fonts/Saira-Italic.ttf
          style: italic
