name: io_flip
description: Google I/O FLIP game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-417.3.beta <4.0.0"
  flutter: 3.10.0-1.4.pre

dependencies:
  api_client:
    path: packages/api_client
  audioplayers: ^3.0.1
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.1
  cloud_firestore: ^4.5.0
  code_text_field: ^1.1.0
  collection: ^1.17.0
  connection_repository:
    path: packages/connection_repository
  cross_file: ^0.3.3+4
  equatable: ^2.0.5
  firebase_app_check: ^0.1.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.5.0
  firebase_crashlytics: ^3.1.0
  firebase_storage: ^11.1.0
  flame:
    git:
      url: https://github.com/willhlas/flame
      path: packages/flame
      ref: main
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  game_domain:
    path: api/packages/game_domain
  game_script_machine:
    path: api/packages/game_script_machine
  go_router: ^6.5.8
  highlight: ^0.7.0
  intl: ^0.18.0
  io_flip_ui:
    path: packages/io_flip_ui
  logging: ^1.1.1
  match_maker_repository:
    path: packages/match_maker_repository
  provider: ^6.0.5
  share_plus: ^6.3.1
  shared_preferences: ^2.1.0
  styled_text: ^7.0.0
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  fake_async: ^1.3.1
  flutter_gen_runner: ^5.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  plugin_platform_interface: ^2.1.4
  url_launcher_platform_interface: ^2.1.2
  very_good_analysis: ^4.0.0

dependency_overrides:
  intl: ^0.17.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/desktop/
    - assets/images/mobile/
    - assets/images/leaderboard/
    - assets/music/
    - assets/sfx/
