name: top_dash
description: Google I/Os Top Dash game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.2

dependencies:
  audioplayers: ^3.0.1
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.8
  firebase_core: ^2.5.0
  firebase_crashlytics: ^3.0.12
  firebase_storage: ^11.0.13
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  game_client:
    path: packages/game_client
  game_domain:
    path: api/packages/game_domain
  go_router: ^6.0.9
  intl: ^0.17.0
  logging: ^1.1.1
  provider: ^6.0.5
  shared_preferences: ^2.0.17

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
