name: top_dash
description: Google I/Os Top Dash game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.2

dependencies:
  api_client:
    path: packages/api_client
  audioplayers: ^3.0.1
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.1
  cloud_firestore: ^4.4.3
  code_text_field: ^1.1.0
  equatable: ^2.0.5
  firebase_auth: ^4.2.9
  firebase_core: ^2.5.0
  firebase_crashlytics: ^3.0.15
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  formz: ^0.5.0+1
  game_domain:
    path: api/packages/game_domain
  game_script_machine:
    path: api/packages/game_script_machine
  go_router: ^6.2.0
  highlight: ^0.7.0
  intl: ^0.17.0
  logging: ^1.1.1
  match_maker_repository:
    path: packages/match_maker_repository
  provider: ^6.0.5
  share_plus: ^6.3.1
  shared_preferences: ^2.0.20
  top_dash_ui:
    path: packages/top_dash_ui
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.1
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
