name: prompt_repository
description: Access to Prompt datasource.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-134.0.dev <4.0.0"

dependencies:
  db_client:
    path: ../db_client
  game_domain:
    path: ../game_domain

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
