name: encryption_middleware
description: A dart_frog middleware for encrypting responses.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  encrypt: ^5.0.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
