name: authentication_repository
description: Repository to manage authentication.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-134.0.dev <4.0.0"
  flutter: 3.9.0-0.2.pre

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.2.9
  firebase_core: ^2.5.0
  firebase_core_platform_interface: ^4.5.3
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
