name: jwt_middleware
description: A dart_frog middleware for checking JWT authorization.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: ^1.1.1
  dart_frog: ^0.3.0
  equatable: ^2.0.5
  http: ^0.13.5
  jose: ^0.3.3
  x509: ^0.2.3

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
