name: gcloud_pubsub
description: A package to manages a cloud run topic.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-134.0.dev <4.0.0"

dependencies:
  grpc: ^3.1.0
  http: ^0.13.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
