name: language_model_repository
description: Repository providing access language model services
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-134.0.dev <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
