name: api
description: Top Dash Game APIs
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  card_renderer:
    path: packages/card_renderer
  cards_repository:
    path: packages/cards_repository
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.3
  db_client:
    path: packages/db_client
  encryption_middleware:
    path: packages/encryption_middleware
  firebase_cloud_storage:
    path: packages/firebase_cloud_storage
  game_domain:
    path: packages/game_domain
  game_script_machine:
    path: packages/game_script_machine
  gcp: ^0.1.0
  image_model_repository:
    path: packages/image_model_repository
  json_annotation: ^4.8.0
  jwt_middleware:
    path: packages/jwt_middleware
  language_model_repository:
    path: packages/language_model_repository
  leaderboard_repository:
    path: packages/leaderboard_repository
  logging: ^1.1.1
  match_repository:
    path: packages/match_repository
  mustache_template: ^2.0.0
  prompt_repository:
    path: packages/prompt_repository
  scripts_repository:
    path: packages/scripts_repository
  shelf_cors_headers: ^0.1.4
  shelf_web_socket: ^1.0.3

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
  web_socket_client: ^0.1.0-dev.1
