name: authentication_repository

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/authentication_repository/**"
      - ".github/workflows/authentication_repository.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1.12.0
    with:
      flutter_channel: stable
      flutter_version: 3.10.0
      working_directory: packages/authentication_repository
