name: io_flip_ui

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/io_flip_ui/**"
      - ".github/workflows/io_flip_ui.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1.12.0
    with:
      flutter_channel: beta
      flutter_version: 3.10.0
      working_directory: packages/io_flip_ui
